name: cup_tub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/Screenshot 2025-04-19 010051.png


#flutter_native_splash:
#  color: "#FFFFFF"
#  color_dark: "#000000"
#  image: assets/logos/Screenshot 2025-04-19 010051.png
##  image_dark: assets/logos/Screenshot 2025-04-19 010051.png
#
#  android_12:
#    color: "#FFFFFF"
#    color_dark: "#000000"
#    image: assets/logos/Screenshot 2025-04-19 010051.png
##    image_dark: assets/logos/Screenshot 2025-04-19 010051.png
#
##  web: false


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
