name: cup_tub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3
  get: ^4.6.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/green-tea.png
    - assets/icons/chips.png
    - assets/icons/coffee-cup.png
    - assets/icons/cookie.png
    - assets/icons/orange-juice.png
    - assets/icons/popcorn.png
    - assets/icons/tea.png


    


